// <auto-generated />
using System;
using JornadaDaTerra.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace JornadaDaTerra.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Fazenda", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                b.Property<double>("AreaHectares").HasColumnType("BINARY_DOUBLE");

                b.Property<string>("Estado")
                    .IsRequired()
                    .IsFixedLength()
                    .HasMaxLength(2)
                    .HasColumnType("NCHAR(2)");

                b.Property<double>("Latitude").HasColumnType("BINARY_DOUBLE");

                b.Property<double>("Longitude").HasColumnType("BINARY_DOUBLE");

                b.Property<string>("Municipio")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("NVARCHAR2(120)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("NVARCHAR2(120)");

                b.Property<int>("ProdutorId").HasColumnType("NUMBER(10)");

                b.HasKey("Id");

                b.HasIndex("ProdutorId");

                b.ToTable("FAZENDAS");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.LeituraSatelite", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("DataLeitura").HasColumnType("TIMESTAMP(7)");

                b.Property<double>("Ndvi").HasColumnType("BINARY_DOUBLE");

                b.Property<double>("PrecipitacaoMm").HasColumnType("BINARY_DOUBLE");

                b.Property<int>("RiscoCalculado").HasColumnType("NUMBER(10)");

                b.Property<int>("SetorId").HasColumnType("NUMBER(10)");

                b.Property<double>("TemperaturaC").HasColumnType("BINARY_DOUBLE");

                b.Property<double>("UmidadeRelativa").HasColumnType("BINARY_DOUBLE");

                b.HasKey("Id");

                b.HasIndex("SetorId");

                b.ToTable("LEITURAS_SATELITE");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Missao", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime?>("ConcluidaEm").HasColumnType("TIMESTAMP(7)");

                b.Property<DateTime>("CriadaEm").HasColumnType("TIMESTAMP(7)");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(600)
                    .HasColumnType("NVARCHAR2(600)");

                b.Property<int?>("LeituraSateliteId").HasColumnType("NUMBER(10)");

                b.Property<DateTime?>("PrazoEm").HasColumnType("TIMESTAMP(7)");

                b.Property<int>("Prioridade").HasColumnType("NUMBER(10)");

                b.Property<int>("RecompensaPontos").HasColumnType("NUMBER(10)");

                b.Property<int>("SetorId").HasColumnType("NUMBER(10)");

                b.Property<int>("Status").HasColumnType("NUMBER(10)");

                b.Property<int>("Tipo").HasColumnType("NUMBER(10)");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("NVARCHAR2(150)");

                b.HasKey("Id");

                b.HasIndex("LeituraSateliteId");

                b.HasIndex("SetorId");

                b.HasIndex("Status");

                b.ToTable("MISSOES");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Produtor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CriadoEm").HasColumnType("TIMESTAMP(7)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(180)
                    .HasColumnType("NVARCHAR2(180)");

                b.Property<int>("Nivel").HasColumnType("NUMBER(10)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("NVARCHAR2(120)");

                b.Property<int>("Pontos").HasColumnType("NUMBER(10)");

                b.HasKey("Id");

                b.HasIndex("Email").IsUnique();

                b.ToTable("PRODUTORES");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Setor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                b.Property<double>("AreaHectares").HasColumnType("BINARY_DOUBLE");

                b.Property<string>("Cultura")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("NVARCHAR2(80)");

                b.Property<int>("FazendaId").HasColumnType("NUMBER(10)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("NVARCHAR2(120)");

                b.HasKey("Id");

                b.HasIndex("FazendaId");

                b.ToTable("SETORES");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Fazenda", b =>
            {
                b.HasOne("JornadaDaTerra.Api.Domain.Entities.Produtor", "Produtor")
                    .WithMany("Fazendas")
                    .HasForeignKey("ProdutorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Produtor");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.LeituraSatelite", b =>
            {
                b.HasOne("JornadaDaTerra.Api.Domain.Entities.Setor", "Setor")
                    .WithMany("Leituras")
                    .HasForeignKey("SetorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Setor");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Missao", b =>
            {
                b.HasOne("JornadaDaTerra.Api.Domain.Entities.LeituraSatelite", "LeituraSatelite")
                    .WithMany()
                    .HasForeignKey("LeituraSateliteId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("JornadaDaTerra.Api.Domain.Entities.Setor", "Setor")
                    .WithMany("Missoes")
                    .HasForeignKey("SetorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LeituraSatelite");

                b.Navigation("Setor");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Produtor", b =>
            {
                b.Navigation("Fazendas");
            });

            modelBuilder.Entity("JornadaDaTerra.Api.Domain.Entities.Setor", b =>
            {
                b.Navigation("Leituras");

                b.Navigation("Missoes");
            });
#pragma warning restore 612, 618
        }
    }
}
